name: riverpod_extension
description: Riverpod extensions
version: 1.0.0
homepage: https://github.com/NickBalnaves/riverpod_extension

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.6.1
  firebase_core: ^1.4.0
  firebase_performance: ^0.7.0+7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_secure_storage: ^4.2.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^0.14.0+4
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter:
