name: riverpod_extension
description: Handy riverpod extensions. To aid in building applications which uses the riverpod package
version: 1.5.0-dev.0
homepage: https://github.com/NickBalnaves/riverpod_extension

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.8.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_state_notifier: ^0.7.1
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^2.0.0-dev.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^4.8.1
  flutter_test:
    sdk: flutter

flutter:
