name: riverpod_extension
description: Handy riverpod extensions. To aid in building applications which uses the riverpod package
version: 1.5.1-dev.0
homepage: https://github.com/NickBalnaves/riverpod_extension

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.8.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_state_notifier: ^0.7.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.0.0-dev.8
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter

flutter:
